#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${AIRFLOW_DB_USER}') THEN
    CREATE USER ${AIRFLOW_DB_USER} WITH PASSWORD '${AIRFLOW_DB_PASSWORD}';
  END IF;

  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${SUPERSET_DB_USER}') THEN
    CREATE USER ${SUPERSET_DB_USER} WITH PASSWORD '${SUPERSET_DB_PASSWORD}';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE ${AIRFLOW_DB} OWNER ${AIRFLOW_DB_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${AIRFLOW_DB}')\gexec

SELECT 'CREATE DATABASE ${SUPERSET_DB} OWNER ${SUPERSET_DB_USER}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${SUPERSET_DB}')\gexec
SQL
